### ISSUE TITLE
Tests fail (with Dist::Zilla 6?)

### ISSUE THREAD

**Issue by eserte** [dagolden/Dist-Zilla-PluginBundle-DAGOLDEN#10]
My smokers started to report the following test fail:
```
[@DAGOLDEN/NextRelease] failed to find Changes in the distribution at /usr/perl5.20.1Dp/lib/site_perl/5.20.1/amd64-freebsd-ld/Moose/Meta/Method/Delegation.pm line 110.
t/dagolden.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```

It could be caused by Dist::Zilla 6, but statistical analysis is not very clear about it:
http://analysis.cpantesters.org/solved?distv=Dist-Zilla-PluginBundle-DAGOLDEN-0.076

**Comment by xdg** [comment]
Thanks.  I'll dig into it.  I'm at YAPC and Rik is here, so have an expert at hand if I need one.  :-)

**Comment by xdg** [comment]
It was a change in Dist::Zilla 6.005.  Fixed and shipped to CPAN.

**Comment by karenetheridge** [comment]
It doesn't look like anything meaningful changed in the distribution, either in commits or generated files?

**Comment by xdg** [comment]
I added an empty "Changes" file to the test distribution corpus: https://github.com/dagolden/Dist-Zilla-PluginBundle-DAGOLDEN/blob/master/corpus/DZ1/Changes

**Comment by karenetheridge** [comment]
aha! I missed that. :)
